# Generated by Django 5.1.4 on 2026-06-25 08:29

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InterviewProfile',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('role', models.CharField(choices=[('frontend', 'Frontend Developer'), ('backend', 'Backend Developer'), ('fullstack', 'Full-Stack Developer'), ('data_science', 'Data Scientist'), ('devops', 'DevOps Engineer'), ('mobile', 'Mobile Developer'), ('ml_engineer', 'ML Engineer'), ('system_design', 'System Design')], max_length=30)),
                ('experience', models.CharField(choices=[('junior', 'Junior (0-2 years)'), ('mid', 'Mid-Level (2-5 years)'), ('senior', 'Senior (5-8 years)'), ('lead', 'Lead (8+ years)')], max_length=20)),
                ('tech_stack', models.JSONField(default=list, help_text='List of technologies')),
                ('num_questions', models.IntegerField(default=5)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='InterviewSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('setup', 'Setup'), ('in_progress', 'In Progress'), ('completed', 'Completed'), ('cancelled', 'Cancelled')], default='setup', max_length=20)),
                ('current_question_index', models.IntegerField(default=0)),
                ('total_score', models.FloatField(default=0.0)),
                ('max_score', models.FloatField(default=0.0)),
                ('proctoring_violations', models.IntegerField(default=0)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='sessions', to='api.interviewprofile')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ProctoringLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('violation_type', models.CharField(choices=[('no_face', 'No Face Detected'), ('multiple_faces', 'Multiple Faces Detected'), ('looking_away', 'Looking Away'), ('tab_switch', 'Tab Switch Detected'), ('face_partially_visible', 'Face Partially Visible')], max_length=30)),
                ('description', models.TextField(blank=True)),
                ('timestamp_seconds', models.FloatField(help_text='Seconds since session started')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='proctoring_logs', to='api.interviewsession')),
            ],
            options={
                'ordering': ['timestamp_seconds'],
            },
        ),
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('text', models.TextField()),
                ('difficulty', models.CharField(choices=[('easy', 'Easy'), ('medium', 'Medium'), ('hard', 'Hard')], default='medium', max_length=10)),
                ('category', models.CharField(blank=True, max_length=100)),
                ('order', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to='api.interviewsession')),
            ],
            options={
                'ordering': ['order'],
            },
        ),
        migrations.CreateModel(
            name='Answer',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('transcript', models.TextField(help_text='Voice-to-text transcript of the answer')),
                ('score', models.FloatField(default=0.0, help_text='AI score from 1-10')),
                ('feedback', models.TextField(blank=True, help_text='Detailed AI feedback')),
                ('strengths', models.JSONField(default=list)),
                ('improvements', models.JSONField(default=list)),
                ('duration_seconds', models.IntegerField(default=0)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('question', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='answer', to='api.question')),
            ],
        ),
    ]
