# Generated by Django 5.1.4 on 2026-06-25 08:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='interviewprofile',
            name='user',
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='is_flagged',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='interviewsession',
            name='strikes',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='proctoringlog',
            name='is_strike',
            field=models.BooleanField(default=False, help_text='Whether this violation counted as a strike'),
        ),
        migrations.AlterField(
            model_name='interviewprofile',
            name='role',
            field=models.CharField(choices=[('frontend', 'Frontend Developer'), ('backend', 'Backend Developer'), ('fullstack', 'Full-Stack Developer'), ('sde', 'Software Development Engineer'), ('data_science', 'Data Scientist'), ('data_analyst', 'Data Analyst'), ('devops', 'DevOps Engineer'), ('mobile', 'Mobile Developer'), ('ml_engineer', 'ML Engineer'), ('system_design', 'System Design'), ('product_manager', 'Product Manager')], max_length=30),
        ),
        migrations.AlterField(
            model_name='proctoringlog',
            name='violation_type',
            field=models.CharField(choices=[('no_face', 'No Face Detected'), ('multiple_faces', 'Multiple Faces Detected'), ('looking_away', 'Looking Away'), ('head_turned', 'Head Turned Sideways'), ('eyes_down', 'Eyes Looking Down'), ('tab_switch', 'Tab Switch Detected'), ('face_partially_visible', 'Face Partially Visible')], max_length=30),
        ),
    ]
