"""
InterviewGuard AI Simulator Models — Interview sessions, questions, answers, and proctoring logs.
"""
import uuid
from django.db import models


class InterviewProfile(models.Model):
    """Configuration for an interview — role, experience, and tech stack."""

    ROLE_CHOICES = [
        ('frontend', 'Frontend Developer'),
        ('backend', 'Backend Developer'),
        ('fullstack', 'Full-Stack Developer'),
        ('sde', 'Software Development Engineer'),
        ('data_science', 'Data Scientist'),
        ('data_analyst', 'Data Analyst'),
        ('devops', 'DevOps Engineer'),
        ('mobile', 'Mobile Developer'),
        ('ml_engineer', 'ML Engineer'),
        ('system_design', 'System Design'),
        ('product_manager', 'Product Manager'),
    ]

    EXPERIENCE_CHOICES = [
        ('junior', 'Junior (0-2 years)'),
        ('mid', 'Mid-Level (2-5 years)'),
        ('senior', 'Senior (5-8 years)'),
        ('lead', 'Lead (8+ years)'),
    ]

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    role = models.CharField(max_length=30, choices=ROLE_CHOICES)
    experience = models.CharField(max_length=20, choices=EXPERIENCE_CHOICES)
    tech_stack = models.JSONField(default=list, help_text="List of technologies")
    num_questions = models.IntegerField(default=5)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"{self.get_role_display()} — {self.get_experience_display()}"


class InterviewSession(models.Model):
    """A single interview session tracking state and results."""

    STATUS_CHOICES = [
        ('setup', 'Setup'),
        ('in_progress', 'In Progress'),
        ('completed', 'Completed'),
        ('cancelled', 'Cancelled'),
    ]

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    profile = models.ForeignKey(InterviewProfile, on_delete=models.CASCADE, related_name='sessions')
    status = models.CharField(max_length=20, choices=STATUS_CHOICES, default='setup')
    current_question_index = models.IntegerField(default=0)
    total_score = models.FloatField(default=0.0)
    max_score = models.FloatField(default=0.0)
    proctoring_violations = models.IntegerField(default=0)
    strikes = models.IntegerField(default=0)
    is_flagged = models.BooleanField(default=False)
    started_at = models.DateTimeField(null=True, blank=True)
    completed_at = models.DateTimeField(null=True, blank=True)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['-created_at']

    def __str__(self):
        return f"Session {self.id} — {self.status}"

    @property
    def score_percentage(self):
        if self.max_score == 0:
            return 0
        return round((self.total_score / self.max_score) * 100, 1)


class Question(models.Model):
    """An interview question generated by Gemini."""

    DIFFICULTY_CHOICES = [
        ('easy', 'Easy'),
        ('medium', 'Medium'),
        ('hard', 'Hard'),
    ]

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    session = models.ForeignKey(InterviewSession, on_delete=models.CASCADE, related_name='questions')
    text = models.TextField()
    difficulty = models.CharField(max_length=10, choices=DIFFICULTY_CHOICES, default='medium')
    category = models.CharField(max_length=100, blank=True)
    order = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['order']

    def __str__(self):
        return f"Q{self.order + 1}: {self.text[:60]}..."


class Answer(models.Model):
    """User's answer to a question, with AI evaluation."""

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    question = models.OneToOneField(Question, on_delete=models.CASCADE, related_name='answer')
    transcript = models.TextField(help_text="Voice-to-text transcript of the answer")
    score = models.FloatField(default=0.0, help_text="AI score from 1-10")
    feedback = models.TextField(blank=True, help_text="Detailed AI feedback")
    strengths = models.JSONField(default=list)
    improvements = models.JSONField(default=list)
    duration_seconds = models.IntegerField(default=0)
    created_at = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f"Answer to Q{self.question.order + 1} — Score: {self.score}/10"


class ProctoringLog(models.Model):
    """Log of proctoring violations detected via computer vision."""

    VIOLATION_CHOICES = [
        ('no_face', 'No Face Detected'),
        ('multiple_faces', 'Multiple Faces Detected'),
        ('looking_away', 'Looking Away'),
        ('head_turned', 'Head Turned Sideways'),
        ('eyes_down', 'Eyes Looking Down'),
        ('tab_switch', 'Tab Switch Detected'),
        ('face_partially_visible', 'Face Partially Visible'),
    ]

    id = models.UUIDField(primary_key=True, default=uuid.uuid4, editable=False)
    session = models.ForeignKey(InterviewSession, on_delete=models.CASCADE, related_name='proctoring_logs')
    violation_type = models.CharField(max_length=30, choices=VIOLATION_CHOICES)
    description = models.TextField(blank=True)
    is_strike = models.BooleanField(default=False, help_text="Whether this violation counted as a strike")
    timestamp_seconds = models.FloatField(help_text="Seconds since session started")
    created_at = models.DateTimeField(auto_now_add=True)

    class Meta:
        ordering = ['timestamp_seconds']

    def __str__(self):
        return f"{self.get_violation_type_display()} at {self.timestamp_seconds}s"
