/**
 * LandingPage — Premium landing page with hero, features, and CTA.
 * Uses Tailwind CSS v4 & Framer Motion for rich light/warm animations.
 */
import { Link } from 'react-router-dom';
import { motion } from 'framer-motion';

export default function LandingPage() {
  const containerVariants = {
    hidden: { opacity: 0 },
    visible: {
      opacity: 1,
      transition: {
        staggerChildren: 0.15,
      },
    },
  };

  const itemVariants = {
    hidden: { opacity: 0, y: 20 },
    visible: { opacity: 1, y: 0, transition: { duration: 0.5, ease: 'easeOut' } },
  };

  return (
    <div className="min-h-screen bg-stone-50 text-stone-900 pt-20 overflow-x-hidden" id="landing-page">
      {/* Hero Section */}
      <section className="relative max-w-6xl mx-auto px-6 py-20 text-center flex flex-col items-center">
        <motion.div
          initial={{ opacity: 0, scale: 0.9 }}
          animate={{ opacity: 1, scale: 1 }}
          transition={{ duration: 0.6 }}
          className="inline-flex items-center gap-1.5 px-3 py-1 rounded-full text-xs font-semibold bg-indigo-50 border border-indigo-100 text-indigo-700 mb-6"
        >
          AI-Powered Mock Interview Simulator
        </motion.div>

        <motion.h1
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6, delay: 0.1 }}
          className="text-4xl sm:text-5xl md:text-6xl font-extrabold tracking-tight text-stone-900 leading-tight max-w-3xl"
        >
          Ace Your Next Interview with{' '}
          <span className="text-indigo-600 font-black">InterviewGuard AI Simulator</span>
        </motion.h1>

        <motion.p
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6, delay: 0.2 }}
          className="text-base sm:text-lg md:text-xl text-stone-600 mt-6 max-w-2xl leading-relaxed"
        >
          A voice-first AI interview simulator with real-time computer vision proctoring.
          Practice speaking answers and receive instant scores & strengths.
        </motion.p>

        <motion.div
          initial={{ opacity: 0, y: 20 }}
          animate={{ opacity: 1, y: 0 }}
          transition={{ duration: 0.6, delay: 0.3 }}
          className="mt-10 flex flex-col sm:flex-row gap-4"
        >
          <Link
            to="/setup"
            id="cta-start"
            className="px-8 py-3.5 rounded-xl font-semibold text-white bg-indigo-600 hover:bg-indigo-700 active:bg-indigo-800 shadow-md hover:shadow-lg transition-all text-center flex items-center justify-center gap-2 cursor-pointer text-sm"
          >
            Start Mock Interview
          </Link>
          <a
            href="#features"
            className="px-8 py-3.5 rounded-xl font-semibold text-stone-700 bg-white hover:bg-stone-100 border border-stone-200 shadow-sm transition-all text-center flex items-center justify-center cursor-pointer text-sm"
          >
            Learn More
          </a>
        </motion.div>
      </section>

      {/* Features Grid Section */}
      <section className="bg-white border-y border-stone-200/85 py-24" id="features">
        <div className="max-w-6xl mx-auto px-6">
          <div className="text-center max-w-xl mx-auto mb-16">
            <h2 className="text-3xl font-bold tracking-tight text-stone-900">
              Why Practice with InterviewGuard AI Simulator?
            </h2>

          </div>

          <motion.div
            variants={containerVariants}
            initial="hidden"
            whileInView="visible"
            viewport={{ once: true, margin: '-100px' }}
            className="grid sm:grid-cols-2 lg:grid-cols-3 gap-8"
          >
            {[
              {
                title: 'Voice-First Experience',
                desc: 'Speak answers naturally. Integrated speech recognition processes your voice directly in real-time.',
              },
              {
                title: 'Adaptive Questions',
                desc: 'Adaptive questions generated by Gemini AI tailored to your selected role, tech stack, and difficulty level.',
              },
              {
                title: 'Gaze & Face Proctoring',
                desc: 'Webcam-based gaze tracking powered by local TensorFlow.js. Highlights distraction to simulate interview integrity.',
              },
              {
                title: 'Immediate AI Feedback',
                desc: 'Instantly get scoring, specific strengths list, and actionable recommendations right after each question.',
              },
              {
                title: 'Comprehensive Reports',
                desc: 'Review your past interviews with detailed metrics, transcripts, and AI-driven insights to track improvement.',
              },
              {
                title: '100% Client-Side Privacy',
                desc: 'Computer vision face tracking runs inside your local browser tab. No camera video is ever uploaded.',
              },
            ].map((feature, idx) => (
              <motion.div
                key={idx}
                variants={itemVariants}
                className="p-6 rounded-2xl border border-stone-200 bg-stone-50/50 hover:bg-stone-50 transition-colors flex flex-col justify-center"
              >
                <h3 className="text-lg font-bold text-stone-900 mb-2">{feature.title}</h3>
                <p className="text-xs text-stone-500 leading-relaxed mt-2">{feature.desc}</p>
              </motion.div>
            ))}
          </motion.div>
        </div>
      </section>

      {/* CTA Box */}
      <section className="bg-indigo-50 border-t border-indigo-100 py-20 text-center px-6">
        <div className="max-w-xl mx-auto">
          <h2 className="text-3xl font-extrabold text-stone-900 mb-4">
            Ready to Ace Your Interview?
          </h2>
          <p className="text-stone-600 mb-8 text-sm">
            Create a mock practice session in a few seconds. No authentication or login required.
          </p>
          <Link
            to="/setup"
            className="inline-flex px-8 py-3.5 rounded-xl font-semibold text-white bg-indigo-600 hover:bg-indigo-700 active:bg-indigo-800 transition-colors shadow-sm cursor-pointer text-sm"
          >
            Begin Practice Session
          </Link>
        </div>
      </section>

    </div>
  );
}
